### PR TITLE
Fix for writing mda files to subdirectories on Linux

### LINKED ISSUE #32: Saving mda files to subdirectories on Linux is broken
PR #27 broke saving to subdirectories on Linux.

### PR DESCRIPTION
**Pull request by kmpeters**
Use a local copy of the filename so trailing slashes can be excluded from the stat call while the filename remains unchanged.

Fixes #32

### CODE REVIEW

**Comment by kmpeters** [comment]
This PR has been tested on RHEL9 and Windows 11 with base-7.0.8.  saveData was able to write data to the correct subdirectories, as well as to the file system path when the subdirectory was blank.

**Comment by timmmooney** [comment]
I'm ok with this fix.

File: sscanApp/src/saveData_writeXDR.c [hunk 1]
```diff
@@ -719,23 +719,32 @@ LOCAL int fileStatus(char* fname)
 {
 	struct stat status;
 	int retVal;
-
+
```
Comment (prjemian) [inline sscanApp/src/saveData_writeXDR.c:722]: remove the trailing whitespace

Comment (kmpeters) [reply sscanApp/src/saveData_writeXDR.c:722]: This whitespace makes the indentation consistent across the entire function (see attached screenshot).

Screenshot from 2024-07-24 15-02-09

Comment (prjemian) [reply sscanApp/src/saveData_writeXDR.c:722]: OK

**Review by keenanlang — APPROVED** [review]
